exit

diff --git a/apptainer.ompi41x/Singularity b/apptainer.ompi41x/Singularity
--- a/apptainer.ompi41x/Singularity
+++ b/apptainer.ompi41x/Singularity
@@ -236,7 +236,7 @@ echo ARMCI_NETWORK is $ARMCI_NETWORK \
              export CMAKE_OPTIONS 
 	     echo CMAKE_OPTIONS $CMAKE_OPTIONS 
 	     CC="$CC" CXX="$CXX" FC="$FC" cmake  $CMAKE_OPTIONS .. || { echo "Cmake failure"; exit 1; } 
-             make V=1 VERBOSE=1 -j3 || { echo "Compilation failure"; exit 1 } 
+             make V=1 VERBOSE=1 -j3 || { echo "Compilation failure"; exit 1; } 
 	     echo exit code for compilation $? 
              make install 
 	     echo exit code for make install $? 
