one

diff --git a/apptainer.ompi41x/Singularity b/apptainer.ompi41x/Singularity
--- a/apptainer.ompi41x/Singularity
+++ b/apptainer.ompi41x/Singularity
@@ -201,49 +201,49 @@ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-"$CUDA_VERSION_MAJOR"."$
 export PATH=$PATH:"$ROCM_PATH"/bin
 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$ROCM_PATH"/lib
 #export ARMCI_NETWORK=MPI-PR
-if [ $(command -v mpicc) ]; then echo mpicc present; else echo mpicc missing; exit 1; fi
-echo "which mpicc is" $(which mpicc) 
-echo "mpicc -show is " $(mpicc -show)  || { tail -700 $ompi_prefix/config.log ;echo "mpi compilation failed"; exit 1; }
-echo ARMCI_NETWORK is $ARMCI_NETWORK \
-	     echo TAMM_BRANCH is ${TAMM_BRANCH} 
-	     echo 'cloning tamm source *** ' || true 
-             cd /opt || { echo "Failure"; exit 1; } 
-             git clone -b ${TAMM_BRANCH} --depth 100  https://github.com/ExaChem/exachem.git CoupledCluster  
-             git clone --depth 100 https://github.com/NWChemEx/TAMM.git 
-	     cd TAMM 
-             git reset --hard 2033f021e0ff20c983a7ba2e9bd7e7cb2441bec6 
-	     mkdir build && cd build 
-             CMAKE_OPTIONS="-DCMAKE_INSTALL_PREFIX=/opt/install/CC -DMODULES=CC " 
-	     CMAKE_OPTIONS="$CMAKE_OPTIONS -DBLIS_CONFIG=zen3 -DMARCH_FLAGS=-march=znver3" 
-	     CMAKE_OPTIONS="$CMAKE_OPTIONS -DCMAKE_Fortran_FLAGS=-O0" 
-             if [ ${GPU} = "nvidia" ]; then echo "nvidia gpu "; CMAKE_OPTIONS="$CMAKE_OPTIONS -DUSE_CUDA=ON -DGPU_ARCH=70" ; fi 
-             if [ ${GPU} = "amd" ]; then echo "amd gpu "; CMAKE_OPTIONS="$CMAKE_OPTIONS -DUSE_HIP=ON -DROCM_ROOT=$ROCM_PATH -DGPU_ARCH=gfx90a -DGCCROOT=/usr " ; ls -lrt $ROCM_PATH/include/rocblas/rocblas.h $ROCM_PATH/include/ ; ln -sf $ROCM_PATH/include/rocblas/rocblas.h $ROCM_PATH/include/rocblas.h; fi 
-             export CMAKE_OPTIONS 
-	     echo CMAKE_OPTIONS $CMAKE_OPTIONS 
-	     CC="$CC" CXX="$CXX" FC="$FC" cmake  $CMAKE_OPTIONS .. || { echo "Cmake failure"; exit 1; } 
-             make V=1 VERBOSE=1 -j3 || { echo "Compilation failure"; 
+if [ $(command -v mpicc) ]; then echo mpicc present; else echo mpicc missing; exit 1; fi \
+&& echo "which mpicc is" $(which mpicc)  \
+&& echo "mpicc -show is " $(mpicc -show)  || { tail -700 $ompi_prefix/config.log ;echo "mpi compilation failed"; exit 1; } \
+&& echo ARMCI_NETWORK is $ARMCI_NETWORK \ 
+&& 	     echo TAMM_BRANCH is ${TAMM_BRANCH}  \
+&& 	     echo 'cloning tamm source *** ' || true  \
+&&              cd /opt || { echo "Failure"; exit 1; }  \
+&&              git clone -b ${TAMM_BRANCH} --depth 100  https://github.com/ExaChem/exachem.git CoupledCluster   \
+&&              git clone --depth 100 https://github.com/NWChemEx/TAMM.git  \
+&& 	     cd TAMM  \
+&&              git reset --hard 2033f021e0ff20c983a7ba2e9bd7e7cb2441bec6  \
+&& 	     mkdir build && cd build  \
+&&              CMAKE_OPTIONS="-DCMAKE_INSTALL_PREFIX=/opt/install/CC -DMODULES=CC "  \
+&& 	     CMAKE_OPTIONS="$CMAKE_OPTIONS -DBLIS_CONFIG=zen3 -DMARCH_FLAGS=-march=znver3"  \
+&& 	     CMAKE_OPTIONS="$CMAKE_OPTIONS -DCMAKE_Fortran_FLAGS=-O0"  \
+&&              if [ ${GPU} = "nvidia" ]; then echo "nvidia gpu "; CMAKE_OPTIONS="$CMAKE_OPTIONS -DUSE_CUDA=ON -DGPU_ARCH=70" ; fi  \
+&&              if [ ${GPU} = "amd" ]; then echo "amd gpu "; CMAKE_OPTIONS="$CMAKE_OPTIONS -DUSE_HIP=ON -DROCM_ROOT=$ROCM_PATH -DGPU_ARCH=gfx90a -DGCCROOT=/usr " ; ls -lrt $ROCM_PATH/include/rocblas/rocblas.h $ROCM_PATH/include/ ; ln -sf $ROCM_PATH/include/rocblas/rocblas.h $ROCM_PATH/include/rocblas.h; fi  \
+&&              export CMAKE_OPTIONS  \
+&& 	     echo CMAKE_OPTIONS $CMAKE_OPTIONS  \
+&& 	     CC="$CC" CXX="$CXX" FC="$FC" cmake  $CMAKE_OPTIONS .. || { echo "Cmake failure"; exit 1; }  \
+&&             make -j3 || { echo "Compilation failure"; 
 	    cat /opt/TAMM/build/TAMM_External-prefix/src/TAMM_External-build/GlobalArrays_External-prefix/src/GlobalArrays_External-build/CMakeFiles/CMakeOutput.log || true ; \
-            cat /opt/TAMM/build/TAMM_External-prefix/src/TAMM_External-build/GlobalArrays_External-prefix/src/GlobalArrays_External-build/CMakeFiles/CMakeError.log || true; exit 1; } 
-	     echo exit code for TAMM compilation $? 
-             make install 
-	     echo exit code for TAMM make install $? 
-             cd /opt/CoupledCluster 
-             git reset --hard eb5181c6fd8aa046388d82e01ee485d92ab78fa9 
-	     mkdir build && cd build 
-	     echo ' === ls -l /opt/install/CC ===' $(ls -l /opt/install/CC) 
-	     echo ' === ls -l /opt/install/CC/lib ===' $(ls -l /opt/install/CC/lib) 
-	     if [ -f /opt/install/CC/lib/libint2.a ]; then echo 'found libint cache' ; \
+            cat /opt/TAMM/build/TAMM_External-prefix/src/TAMM_External-build/GlobalArrays_External-prefix/src/GlobalArrays_External-build/CMakeFiles/CMakeError.log || true; exit 1; } \
+&& 	     echo exit code for TAMM compilation $?  \
+&&              make install  \
+&& 	     echo exit code for TAMM make install $?  \
+&&              cd /opt/CoupledCluster  \
+&&              git reset --hard eb5181c6fd8aa046388d82e01ee485d92ab78fa9  \
+&& 	     mkdir build && cd build  \
+&& 	     echo ' === ls -l /opt/install/CC ===' $(ls -l /opt/install/CC)  \
+&& 	     echo ' === ls -l /opt/install/CC/lib ===' $(ls -l /opt/install/CC/lib)  \
+&& 	     if [ -f /opt/install/CC/lib/libint2.a ]; then echo 'found libint cache' ; \ 
              mkdir -p /opt/CoupledCluster/build/stage/opt || true ; \
-	     rsync -av /opt/install /opt/CoupledCluster/build/stage/opt/. ; fi 
-             export CMAKE_OPTIONS 
-	     echo CMAKE_OPTIONS $CMAKE_OPTIONS 
-	     CC="$CC" CXX="$CXX" FC="$FC" cmake  $CMAKE_OPTIONS .. || { echo "Cmake failure"; exit 1; } 
-             make V=1 VERBOSE=1 -j3 || { echo "Compilation failure"; exit 1; } 
-	     echo exit code for compilation $? 
-             make install 
-	     echo exit code for make install $? 
-	     bash -c "if [[ -f /opt/install/CC/bin/ExaChem ]]; then echo 'Exachem binary created' ; else  echo 'compilation error1'; exit 1; fi" 
-	     echo git describe --always `git describe --always`  >> /opt/install/info.txt \
+	     rsync -av /opt/install /opt/CoupledCluster/build/stage/opt/. ; fi  \
+&&              export CMAKE_OPTIONS  \
+&& 	     echo CMAKE_OPTIONS $CMAKE_OPTIONS  \
+&& 	     CC="$CC" CXX="$CXX" FC="$FC" cmake  $CMAKE_OPTIONS .. || { echo "Cmake failure"; exit 1; }  \
+&&              make V=1 VERBOSE=1 -j3 || { echo "Compilation failure"; exit 1; }  \
+&& 	     echo exit code for compilation $?  \
+&&              make install  \
+&& 	     echo exit code for make install $?  \
+&& 	     bash -c "if [[ -f /opt/install/CC/bin/ExaChem ]]; then echo 'Exachem binary created' ; else  echo 'compilation error1'; exit 1; fi"  \
+&& 	     echo git describe --always `git describe --always`  >> /opt/install/info.txt \ 
 	    && echo git rev-parse HEAD git `git rev-parse HEAD` >> /opt/install/info.txt \
             && echo 'clean unnecessary source to reduce docker size' \
             && cd /opt && rm  -rf CoupledCluster \
