one

diff --git a/apptainer.ompi41x/Singularity b/apptainer.ompi41x/Singularity
--- a/apptainer.ompi41x/Singularity
+++ b/apptainer.ompi41x/Singularity
@@ -220,18 +220,18 @@ if [ $(command -v mpicc) ]; then echo mpicc present; else echo mpicc missing; ex
 &&              if [ ${GPU} = "amd" ]; then echo "amd gpu "; CMAKE_OPTIONS="$CMAKE_OPTIONS -DUSE_HIP=ON -DROCM_ROOT=$ROCM_PATH -DGPU_ARCH=gfx90a -DGCCROOT=/usr " ; ls -lrt $ROCM_PATH/include/rocblas/rocblas.h $ROCM_PATH/include/ ; ln -sf $ROCM_PATH/include/rocblas/rocblas.h $ROCM_PATH/include/rocblas.h; fi  \
 &&              export CMAKE_OPTIONS  \
 && 	     echo CMAKE_OPTIONS $CMAKE_OPTIONS  \
-&& 	     CC="$CC" CXX="$CXX" FC="$FC" cmake  $CMAKE_OPTIONS .. || { echo "Cmake failure"; exit 1; }  \
-&&             make -j3 || { echo "Compilation failure"; 
+&& 	     CC="$CC" CXX="$CXX" FC="$FC" cmake  $CMAKE_OPTIONS .. || { echo "Cmake failure"; exit 1; }  
+             make -j3 || { echo "Compilation failure"; 
 	    cat /opt/TAMM/build/TAMM_External-prefix/src/TAMM_External-build/GlobalArrays_External-prefix/src/GlobalArrays_External-build/CMakeFiles/CMakeOutput.log || true ; \
-            cat /opt/TAMM/build/TAMM_External-prefix/src/TAMM_External-build/GlobalArrays_External-prefix/src/GlobalArrays_External-build/CMakeFiles/CMakeError.log || true; exit 1; } \
-&& 	     echo exit code for TAMM compilation $?  \
-&&              make install  \
-&& 	     echo exit code for TAMM make install $?  \
-&&              cd /opt/CoupledCluster  \
-&&              git reset --hard eb5181c6fd8aa046388d82e01ee485d92ab78fa9  \
-&& 	     mkdir build && cd build  \
-&& 	     echo ' === ls -l /opt/install/CC ===' $(ls -l /opt/install/CC)  \
-&& 	     echo ' === ls -l /opt/install/CC/lib ===' $(ls -l /opt/install/CC/lib)  
+            cat /opt/TAMM/build/TAMM_External-prefix/src/TAMM_External-build/GlobalArrays_External-prefix/src/GlobalArrays_External-build/CMakeFiles/CMakeError.log || true; exit 1; } 
+ 	     echo exit code for TAMM compilation $?  
+              make install  
+ 	     echo exit code for TAMM make install $?  
+              cd /opt/CoupledCluster  
+              git reset --hard eb5181c6fd8aa046388d82e01ee485d92ab78fa9  
+ 	     mkdir build && cd build  
+ 	     echo ' === ls -l /opt/install/CC ===' $(ls -l /opt/install/CC)  
+ 	     echo ' === ls -l /opt/install/CC/lib ===' $(ls -l /opt/install/CC/lib)  
 	     if [ -f /opt/install/CC/lib/libint2.a ]; then echo 'found libint cache' ; \
              mkdir -p /opt/CoupledCluster/build/stage/opt || true ; \
 	     rsync -av /opt/install /opt/CoupledCluster/build/stage/opt/. ; fi 
