knem

diff --git a/apptainer.merge/Singularity b/apptainer.merge/Singularity
--- a/apptainer.merge/Singularity
+++ b/apptainer.merge/Singularity
@@ -323,6 +323,32 @@ echo 'CXX -v ' `$CXX -v` || { echo "CXX not installed"; exit  1; }
 apt-get clean 
 export ORGPWD=$(pwd)
 echo ORGPWD is $ORGPWD
+#installing knem
+echo 'ls -l /opt/mpi/include/knem_io.h' $(ls -l /opt/mpi/include/knem_io.h) || true
+if [ ! -f /opt/mpi/include/knem_io.h ]; then
+    export knem=1.1.4
+    export ktag=$(dpkg-query -s linux-headers-generic|egrep Dep|cut -d " " -f 2 | sed -e s'/linux-headers-//')
+    echo ktag is $ktag
+    ls /lib/modules/$ktag  || true
+    wget https://gitlab.inria.fr/knem/knem/uploads//4a43e3eb860cda2bbd5bf5c7c04a24b6/knem-$knem.tar.gz -O - | tar xzf - 
+    cd knem-$knem
+    echo 'ktag is $ktag'
+    ./configure --prefix=$OMPI_DIR --with-linux-build=/lib/modules/$ktag/build --with-linux-release=$ktag
+    make install-includeHEADERS || { echo "KNEM Installation h Failure"; exit 1; }
+    make install-pkgconfigDATA  || { echo "KNEM Installation p Failure"; exit 1; }
+fi
+#installing xpmem
+echo 'ls -l /opt/mpi/lib/libxpmem.so' $(ls -l /opt/mpi/lib/libxpmem.so) || true
+if [ ! -f /opt/mpi/lib/libxpmem.so ]; then
+    wget --progress=dot:giga https://github.com/Cray-HPE/xpmem/tarball/master -O xpmem.tar.gz 
+    tar xzf xpmem.tar.gz 
+    rm xpmem.tar.gz 
+    cd Cray-HPE-xpmem* 
+    sh autogen.sh 
+    ./configure --prefix=$MPI_DIR --disable-kernel-module  || { echo "XPMEM Configuration Failure"; exit 1; }
+    make -j3 || { echo "XPMEM Compilation Failure"; exit 1; }
+    make install || { echo "XPMEM Installation Failure"; exit 1; }
+fi
 if [ $UCX != "N" ]; then
     echo check ucx install 
     echo 'ls -l /opt/mpi/lib/libuct.so' $(ls -l /opt/mpi/lib/libuct.so) || true 
@@ -419,32 +445,6 @@ if [ $PMIX != "N" ]; then
 	cd .. 
 	rm -rf pmix-*.*
     fi
-fi
-#installing knem
-echo 'ls -l /opt/mpi/include/knem_io.h' $(ls -l /opt/mpi/include/knem_io.h) || true
-if [ ! -f /opt/mpi/include/knem_io.h ]; then
-    export knem=1.1.4
-    export ktag=$(dpkg-query -s linux-headers-generic|egrep Dep|cut -d " " -f 2 | sed -e s'/linux-headers-//')
-    echo ktag is $ktag
-    ls /lib/modules/$ktag  || true
-    wget https://gitlab.inria.fr/knem/knem/uploads//4a43e3eb860cda2bbd5bf5c7c04a24b6/knem-$knem.tar.gz -O - | tar xzf - 
-    cd knem-$knem
-    echo 'ktag is $ktag'
-    ./configure --prefix=$OMPI_DIR --with-linux-build=/lib/modules/$ktag/build --with-linux-release=$ktag
-    make install-includeHEADERS || { echo "KNEM Installation h Failure"; exit 1; }
-    make install-pkgconfigDATA  || { echo "KNEM Installation p Failure"; exit 1; }
-fi
-#installing xpmem
-echo 'ls -l /opt/mpi/lib/libxpmem.so' $(ls -l /opt/mpi/lib/libxpmem.so) || true
-if [ ! -f /opt/mpi/lib/libxpmem.so ]; then
-    wget --progress=dot:giga https://github.com/Cray-HPE/xpmem/tarball/master -O xpmem.tar.gz 
-    tar xzf xpmem.tar.gz 
-    rm xpmem.tar.gz 
-    cd Cray-HPE-xpmem* 
-    sh autogen.sh 
-    ./configure --prefix=$MPI_DIR --disable-kernel-module  || { echo "XPMEM Configuration Failure"; exit 1; }
-    make -j3 || { echo "XPMEM Compilation Failure"; exit 1; }
-    make install || { echo "XPMEM Installation Failure"; exit 1; }
 fi
 cd $ORGPWD
 if [ -n "${OMPI+1}" ]; then
