knem

diff --git a/apptainer.merge/Singularity b/apptainer.merge/Singularity
--- a/apptainer.merge/Singularity
+++ b/apptainer.merge/Singularity
@@ -338,7 +338,7 @@ if [ $UCX != "N" ]; then
 	    patch -p0 < ./ucx1181_malloc.patch
 	fi 
 	mkdir build && cd build 
-	../configure --prefix=$MPI_DIR --disable-logging --disable-debug --disable-assertions --disable-params-check || { echo "UCX config Failure"; exit 1; }
+	../configure --prefix=$MPI_DIR  --disable-logging --disable-debug --disable-assertions --disable-params-check --with-xpmem=$MPI_DIR --with-knem=$MPI_DIR || { echo "UCX config Failure"; exit 1; }
 	make -j4 || { echo "UCX Compilation Failure"; exit 1; }
 	make install || { echo "UCX Installation Failure"; exit 1; }
 	if [ ! -f $MPI_DIR/bin/ucx_info ]; then echo ucx_info\ not\ found ; exit 1 ; fi 
