multiple apptainer pulls

diff --git a/.github/workflows/apptainer_exachem_merge.yaml b/.github/workflows/apptainer_exachem_merge.yaml
--- a/.github/workflows/apptainer_exachem_merge.yaml
+++ b/.github/workflows/apptainer_exachem_merge.yaml
@@ -378,7 +378,19 @@ jobs:
       run: |
         pwd
         ls -la
-        APPTAINER_DISABLE_CACHE=True apptainer pull -F ${{ env.tag }}:${{ env.date }}
+        export APPTAINER_DISABLE_CACHE=True
+        attempts=0
+        max_attempts=3
+        until  apptainer pull -F ${{ env.tag }}:${{ env.date }}  > /dev/null ; do
+            if [  "$attempts" -gt $max_attempts ]; then
+                echo "pull failed after $max_attempts attempts"
+                exit 1
+            else
+                echo "pull failed. sleeping for 5s"
+                sleep 5s
+                attempts+=1
+            fi
+        done
         sudo apt-get install -y openmpi-bin libmpich-dev mpich
         mpirun --version || true
         ldd `which mpirun`
@@ -388,7 +400,19 @@ jobs:
       run: |
         pwd
         ls -la
-        APPTAINER_DISABLE_CACHE=True apptainer pull -F ${{ env.tag }}:${{ env.date }}
+        export APPTAINER_DISABLE_CACHE=True
+        attempts=0
+        max_attempts=3
+        until  apptainer pull -F ${{ env.tag }}:${{ env.date }}  > /dev/null ; do
+            if [  "$attempts" -gt $max_attempts ]; then
+                echo "pull failed after $max_attempts attempts"
+                exit 1
+            else
+                echo "pull failed. sleeping for 5s"
+                sleep 5s
+                attempts+=1
+            fi
+        done
         export UCX_TLS=tcp,self
         export UCX_POSIX_USE_PROC_LINK=n
         export OMPI_MCA_btl_vader_single_copy_mechanism=none
